### ISSUE TITLE
有些appid，例如590830，没有common会导致报错。

### ISSUE THREAD

**Issue by htchennuo1** [newton-miku/SteamIconFixer#1]
![image](https://user-images.githubusercontent.com/85295214/232324133-2d05d703-ef0a-4cb1-a1dd-2821f1eac81a.png)

![image](https://user-images.githubusercontent.com/85295214/232324250-be4eea9e-0e2d-4eb3-bf47-6769aa550e95.png)
（改了下，没学过python，直接文本判断了）
[fixIcon-fixed.txt](https://github.com/newton-miku/SteamIconFixer/files/11242693/fixIcon-fixed.txt)

**Comment by newton-miku** [comment]
这个我研究了下，应该和[Steam py模块仓库](https://github.com/ValvePython/steam/blob/master/steam/client/builtins/apps.py#L68)中所写的描述一样，是当"_missing_token": true时，表示需要访问许可，而我两个脚本中都未要求登陆你自己的账户，故无该许可，因此无法获取相关信息
综上，其实不用判断common，直接看这个_missing_token的值就行（btw，我去steamdb上翻了下，是有相关信息的，但是我没找到相关api，也没看出来这个是个什么游戏，steam商店中访问便跳转回主页

**Comment by htchennuo1** [comment]
这样看的话因为这是个没发售的游戏（s&box，garry's mod续作），目前需要内测资格才能看到信息，所以访问需要token。我昨天看到另一个项目：https://github.com/mrsimb/steam_blank_icon_fix 里用的steamdb页面上的直链抓取的ico，但是他这个项目在我这不工作。
![image](https://user-images.githubusercontent.com/85295214/232685079-d1f7b71d-49e1-4ff6-bc5f-3753867a1c99.png)

Steamdb仍旧是可以抓取图标的：
`https://steamdb.info/app/str(appid)/info/`页面上的**clienticon**栏目里就是ico。查找网页里带.ico的链接既可。

![image](https://user-images.githubusercontent.com/85295214/232683038-dc0e1a17-fd59-4539-a72b-ae6803389cc8.png)

**Comment by newton-miku** [comment]
我知道steamdb里有相关信息，但是没找到相关api，而且因为我之前是没有学过python的，所以不知道怎么获取网页中的url链接。
btw，steamdb是加了机器人检测的，可能是这个原因导致的不工作（顺带说一句，国内的网络访问steamdb某些情况下非常缓慢，因为套了cf的cdn的原因）

**Comment by htchennuo1** [comment]
这样啊，理解了。感谢解答(●'◡'●)
